import { Welcome } from "../state.slint";
import { Theme } from "../theme.slint";
import { ChoiceButton } from "../widgets/choice-button.slint";

export component WelcomePage inherits Rectangle {
    Rectangle {
        width: 220px;
        height: 150px;
        title := Text {
            y: 0;
            width: parent.width;
            height: 32px;
            horizontal-alignment: center;
            font-size: 24px;
            font-weight: 700;
            text: "Welcome!";
            color: white;
        }
        message := Text {
            y: 44px;
            width: parent.width;
            height: 40px;
            font-size: 14px;
            horizontal-alignment: center;
            wrap: word-wrap;
            text: "hr-osc settings were found on this computer. Bring them over?";
            color: Theme.gray-400;
        }
        Rectangle {
            y: 100px;
            height: 36px;
            ChoiceButton {
                x: 0;
                width: parent.width - 4px - 72px;
                text: "Import";
                idle: Theme.accept;
                hover: Theme.accept-hover;
                clicked => {
                    Welcome.import-hr-osc();
                }
            }
            ChoiceButton {
                x: parent.width - 72px;
                width: 72px;
                text: "Skip";
                idle: Theme.decline;
                hover: Theme.decline-hover;
                clicked => {
                    Welcome.skip();
                }
            }
        }
    }
}
