import { Settings } from "../../state.slint";
import { Field } from "../../widgets/field.slint";
import { GroupGap } from "../../widgets/group-gap.slint";
import { Label } from "../../widgets/label.slint";
import { SmallButton } from "../../widgets/small-button.slint";

export component HttpTab inherits VerticalLayout {
    spacing: 8px;
    Label {
        text: "HTTP Server Port:";
    }
    Field {
        number: true;
        text <=> Settings.http-port;
        placeholder: "8080";
        edited(value) => {
            Settings.setting("http_server_port", value);
        }
    }
    GroupGap { }
    SmallButton {
        text: "Restart Server";
        clicked => {
            Settings.restart-source();
        }
    }
}
