import { Theme } from "../theme.slint";

export component NavItem inherits Rectangle {
    in property <string> text;
    in property <bool> active;
    callback clicked();
    width: label.preferred-width;
    height: 26px;
    label := Text {
        y: 0;
        height: 24px;
        vertical-alignment: center;
        text: root.text;
        color: white;
    }
    if root.active: Rectangle {
        y: 24px;
        height: 2px;
        background: Theme.cyan-400;
    }
    TouchArea {
        mouse-cursor: pointer;
        clicked => {
            root.clicked();
        }
    }
}
