import "./fonts/Nunito-Regular.ttf";
import "./fonts/Nunito-Bold.ttf";
import { Theme } from "theme.slint";
import { Navigation, Updates, Welcome } from "state.slint";
import { AboutPage } from "pages/about.slint";
import { Home } from "pages/home.slint";
import { NavBar } from "pages/nav-bar.slint";
import { SettingsPage } from "pages/settings.slint";
import { UpdatePage } from "pages/update.slint";
import { WelcomePage } from "pages/welcome.slint";

export { DeviceRow, HeartRate, Navigation, Settings, Updates, Welcome } from "state.slint";
export { VrPanel } from "vr-panel.slint";

export component AppWindow inherits Window {
    in property <bool> beat;
    in property <bool> on-screen: true;
    title: "Heartwire";
    icon: root.beat ? @image-url("../assets/icon-beat.png") : @image-url("../assets/icon.png");
    width: 325px;
    height: 250px;
    background: Theme.gray-900;
    default-font-family: "Nunito";
    default-font-size: 16px;

    if Welcome.shown: WelcomePage { }

    if !Welcome.shown && Updates.shown: UpdatePage { }

    if !Welcome.shown && !Updates.shown: Rectangle {
        x: 8px;
        y: 8px;
        width: parent.width - 16px;
        height: parent.height - 16px;
        NavBar {
            y: 0;
        }
        Rectangle {
            y: 30px;
            height: parent.height - 30px;
            Home {
                visible: Navigation.page == 0;
                animate: root.on-screen;
            }
            if Navigation.page == 1: SettingsPage { }
            if Navigation.page == 2: AboutPage { }
        }
    }
}
