export global Theme {
    out property <color> gray-900: #111827;
    out property <color> gray-800: #1f2937;
    out property <color> gray-700: #374151;
    out property <color> gray-600: #4b5563;
    out property <color> gray-500: #6b7280;
    out property <color> gray-400: #9ca3af;
    out property <color> red-400: #f87171;
    out property <color> cyan-400: #22d3ee;
    out property <color> lime-500: #84cc16;
    out property <color> rose-500: #f43f5e;
    out property <color> sky-200: #bae6fd;
    out property <color> input: #6b72801a;
    out property <color> selection: #22d3ee55;
    out property <color> update-button: #3f62124d;
    out property <color> update-button-hover: #3f621280;
    out property <color> later-button: #9f12394d;
    out property <color> later-button-hover: #9f123980;
}
